### ISSUE TITLE
Sumbit cluster jobs with fixed scale

### ISSUE THREAD

**Issue by fbradascio** [IceCubeOpenSource/flarestack#10]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't run w/ O(1e3) on the cluster

**Describe the solution you'd like**
Being able to split more the jobs

**Describe alternatives you've considered**
Kill myself.

**Additional context**

**Comment by robertdstein** [comment]
I would advice against your alternative solution.

**Comment by robertdstein** [comment]
I think this feature already exists. You need to specify "fixed_scale" in mh_dict, rather than "scale". You should then get n trials at a specified scale, rather than a standard "n trial at each step".

**Comment by robertdstein** [comment]
Ideally "scale" should be replaced with "max_scale" as a parameter in the code, to avoid this confusion.

**Comment by fbradascio** [comment]
See Issue #11

**Comment by robertdstein** [comment]
This one is a real emotional rollercoaster
