### ISSUE TITLE
"No Background TS Distribution found" when looping over catalogues in Unblinder Class

### ISSUE THREAD

**Issue by fbradascio** [IceCubeOpenSource/flarestack#20]
**Describe the bug**
"No Background TS Distribution found" when using the Unblinder Class for the AGN cores stacking analysis.

**To Reproduce**
1. Run 'flarestack/analyses/agn_cores/scripts_for_unblinding/unblind_agn_cores.py
2. Use setting 'mock_unblinding=True'
3. See error

**Expected behavior**
Obtain upper limits and plots for unblinded results.

**Additional context**
The problem is related to the fact the code originally loops over injection properties, while in this case should loop over sub-catalogues (classified on the number of sources).

**Comment by robertdstein** [comment]
Now fixed with new script for flarestack/analyses/agn_cores/scripts_for_unblinding/unblind_agn_cores.py.
