### ISSUE TITLE
ModuleNotFoundError Notebook examples not working

### ISSUE THREAD

**Issue by bhishmapitamah** [IceCubeOpenSource/flarestack#8]
**Describe the bug**
The example notebooks provided in the docs are inconsistent with the current version of flarestack.

**To Reproduce**
1. Run '0-Setting up Flarestack.ipynb' on binder or locally
2. Run Cells
3. Module error for flarestack.precompute

**Expected behavior**
precompute.py has been removed in the latest release v1.2.2

**Additional context**

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-4779a1682915> in <module>
      1 from pathlib import Path
      2 home = str(Path.home())
----> 3 from flarestack.precompute import run_precompute, set_scratch_directory
      4 set_scratch_directory(home)

ModuleNotFoundError: No module named 'flarestack.precompute'

**Comment by robertdstein** [comment]
That notebook is completely redundant, so should not even be in flarestack any more
.
